[package]
name = "chromic"
version = "0.0.1"
edition = "2021"


[dependencies]
anyhow = "1.0.75"
petgraph = { version = "0.6.3", features = ["stable_graph"] }
smol_str = "0.2.0"

# Needed for GDTF parsing
opengdtf = { git = "https://github.com/Firionus/opengdtf"}
nom = "7.1.3"
